version: 0.2

# env:
#   git_access_token: "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"
#   repo_name: "kubernetes-blue-green-deployment-with-argo-rollout"
#   repo_owner: "captain-omkar"
env:
  variables:
    GITHUB_TOKEN: ${{ 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 }}

phases:
  install:
    commands:
#       - git config --global credential.helper '!aws codecommit credential-helper $@'
#       - git config --global credential.UseHttpPath true
#       - echo $git_access_token
#       - echo "#!/bin/bash\n echo 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" > ~/token-helper.sh
#       - chmod +x ~/token-helper.sh
#       - export GIT_ASKPASS=~/token-helper.sh
#       - git clone https://github.com/captain-omkar/kubernetes-blue-green-deployment-with-argo-rollout.git
#       - cd kubernetes-blue-green-deployment-with-argo-rollout
#       - echo "New line of text" >> file_to_modify.txt
#       - git remote -v
#       - git config --global user.email "omkarchavanbldea@gmail.com"
#       - git config --global user.name "captain-omkar"
      
#       - git add .
      
#       - git commit -m "Commit message"
#       - git push 

#       - git push 
      - git clone https://github.com/captain-omkar/kubernetes-blue-green-deployment-with-argo-rollout.git
      - cd kubernetes-blue-green-deployment-with-argo-rollout
      # Create a file
      - echo "Hello, world!" > hello.txt
      # Set up Git configuration
      - git config --global user.email "omkarchavanbldea@gmail.com"
      - git config --global user.name "captainomkar"
      # Add and commit the file
      - git add hello.txt
      - git commit -m "Add hello.txt"
      # Push the changes
      - git push https://oauth2:${GITHUB_TOKEN}@github.com/captain-omkar/kubernetes-blue-green-deployment-with-argo-rollout.git 
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
      - unzip sonar-scanner-cli-3.3.0.1492-linux.zip
      - export PATH=$PATH:./sonar-scanner-3.3.0.1492-linux/bin/
 
  pre_build:
    commands:
      - mvn clean install
      - echo Logging in to Amazon ECR...
      - aws --version
      - sonar-scanner -X -Dsonar.projectKey=myproj -Dsonar.java.binaries=target/classes -Dsonar.sources=src -Dsonar.host.url=http://52.91.2.145:80 -Dsonar.login=24685e8524aded3a927eb1e72448aff666660a75
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 086349442762.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=086349442762.dkr.ecr.us-east-1.amazonaws.com/loco
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"order-service","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
   - imagedefinitions.json
   - target/*.jar
