version: 0.2

env:
  git_access_token: "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"
  repo_name: "kubernetes-blue-green-deployment-with-argo-rollout"
  repo_owner: "captain-omkar"

phases:
  install:
    commands:
      - git config --global credential.helper '!aws codecommit credential-helper $@'
      - git config --global credential.UseHttpPath true
      - echo "#!/bin/bash\n echo $git_access_token" > ~/token-helper.sh
      - chmod +x ~/token-helper.sh
      - export GIT_ASKPASS=~/token-helper.sh
      - git clone https://github.com/captain-omkar/kubernetes-blue-green-deployment-with-argo-rollout.git
      - cd $repo_name
      - echo "New line of text" >> file_to_modify.txt
      - git init
      - git remote set-url origin https://captain-omkar:$git_access_token@github.com:captain-omkar/kubernetes-blue-green-deployment-with-argo-rollout.git
      - git remote -v
      - git add .
      - git config --global user.email "omkarchavanbldea@gmail.com"
      - git config --global user.name "captain-omkar"
      - git commit -m "Commit message"
      - git push 
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
      - unzip sonar-scanner-cli-3.3.0.1492-linux.zip
      - export PATH=$PATH:./sonar-scanner-3.3.0.1492-linux/bin/
 
  pre_build:
    commands:
      - mvn clean install
      - echo Logging in to Amazon ECR...
      - aws --version
      - sonar-scanner -X -Dsonar.projectKey=myproj -Dsonar.java.binaries=target/classes -Dsonar.sources=src -Dsonar.host.url=http://52.91.2.145:80 -Dsonar.login=24685e8524aded3a927eb1e72448aff666660a75
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 086349442762.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=086349442762.dkr.ecr.us-east-1.amazonaws.com/loco
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"order-service","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
   - imagedefinitions.json
   - target/*.jar
