version: 0.2

phases:
  install:
  
    commands:

      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
      - unzip sonar-scanner-cli-3.3.0.1492-linux.zip
      - export PATH=$PATH:./sonar-scanner-3.3.0.1492-linux/bin/
 
  pre_build:
    commands:
      - mvn clean install
      - echo Logging in to Amazon ECR...
      - aws --version
      - sonar-scanner -X -Dsonar.projectKey=myproj -Dsonar.java.binaries=target/classes -Dsonar.sources=src -Dsonar.host.url=http://<sonar-server-public-ip>:80 -Dsonar.login=<sonar-token>
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <ecr-URI>
      - REPOSITORY_URI=<ecr-URI>
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"order-service","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
      
      - git clone <codecommit-https-url> -c credential.helper='!aws codecommit credential-helper $@' -c credential.UseHttpPath=true
      - cd manifest/base #depends on repo directory its sample one i had in my repo 
      - ls
      - kubectl patch --local -f deployment.yaml -p '{"spec":{"template":{"spec":{"containers":[{"name":"rollouts-demo","image":"'$REPOSITORY_URI:$IMAGE_TAG'"}]}}}}' -o yaml > new-deployment.yaml
      - mv new-deployment.yaml deployment.yaml
      - git config --global user.email "omkarchavanbldea@gmail.com"
      - git config --global user.name "captain-omkar"
      - git add .
      - git commit -m "addedd"
      - git push
artifacts:
  files:
   - imagedefinitions.json
   - target/*.jar
